from django.urls import path
from django.http import JsonResponse
from rest_framework_simplejwt.views import TokenRefreshView
from .views import(
    RegisterView,
    LoginView,
    LogoutView,
    ProfileView,
    ProfileUpdateView,
    AvatarUploadView,
    DeleteAccountView,
    UserDetailView,
    UserStatsView,
    UserMatchHistoryView,
    UserAchievementsView,
    LeaderboardView,
    PasswordChangeView,
    AddFriendView,
    RemoveFriendView,
    FriendListView,
    FriendRequestCreateView,
    FriendRequestsListView,
    AcceptFriendView,
    BlockUserView,
    UnblockUserView,
    BlockedUsersListView,
    OAuth42RedirectView,
    OAuth42CallbackView,
)

def health(request):
    return JsonResponse({"status": "ok", "service": "auth"})

urlpatterns = [
    path('health/', health, name='health'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/avatar/', AvatarUploadView.as_view(), name='avatar-upload'),
    path('delete/', DeleteAccountView.as_view(), name='delete-account'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('users/<int:user_id>/', UserDetailView.as_view(), name="user-detail"),
    path('users/<int:user_id>/stats/', UserStatsView.as_view(), name="user-stats"),
    path('users/<int:user_id>/matches/', UserMatchHistoryView.as_view(), name="user-matches"),
    path('users/<int:user_id>/achievements/', UserAchievementsView.as_view(), name="user-achievements"),
    path('users/block/', BlockUserView.as_view(), name='block-user'),
    path('users/unblock/', UnblockUserView.as_view(), name='unblock-user'),
    path('users/blocked/', BlockedUsersListView.as_view(), name='blocked-users'),
    path('password/change/', PasswordChangeView.as_view(), name='password-change'),
    path('friends/', FriendListView.as_view(), name='friend-list'),
    path('friends/add/', AddFriendView.as_view(), name='add-friend'),
    path('friends/remove/', RemoveFriendView.as_view(), name='remove-friend'),
    path('friends/request/', FriendRequestCreateView.as_view(), name='friend-request-create'),
    path('friends/requests/', FriendRequestsListView.as_view(), name='friend-requests-list'),
    path('friends/accept/', AcceptFriendView.as_view(), name='accept-friend'),
    path('leaderboard/', LeaderboardView.as_view(), name='leaderboard'),
    path('oauth/42/', OAuth42RedirectView.as_view(), name='oauth-42'),
    path('oauth/callback/', OAuth42CallbackView.as_view(), name='oauth-callback'),
]
