# Generated by Django 5.0.14 on 2026-03-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('room_type', models.CharField(choices=[('dm', 'Direct Message'), ('channel', 'Group Channel'), ('tournament', 'Tournament Chat')], default='channel', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('text', models.TextField()),
                ('message_type', models.CharField(choices=[('message', 'Regular Message'), ('system', 'System Message'), ('notification', 'Notification')], default='message', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_app.chatroom')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['room', '-created_at'], name='chat_app_ch_room_id_729b30_idx'), models.Index(fields=['sender_id'], name='chat_app_ch_sender__5ddd53_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat_app.chatroom')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('room', 'user_id')},
            },
        ),
    ]
