# Generated by Django 5.0.14 on 2026-03-28 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_legacy_schema_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue')], max_length=10)),
            ],
            options={
                'ordering': ['team', 'id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='matchrecord',
            name='auth_app_ma_player1_fc0edd_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchrecord',
            name='auth_app_ma_player2_010aeb_idx',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='replay_url',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='score_p1',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='score_p2',
        ),
        migrations.RemoveField(
            model_name='matchrecord',
            name='winner',
        ),
        migrations.AddField(
            model_name='matchrecord',
            name='end_reason',
            field=models.CharField(choices=[('score_limit', 'Score Limit'), ('time_limit', 'Time Limit'), ('time_limit_draw', 'Time Limit Draw'), ('forfeit', 'Forfeit'), ('disconnect', 'Disconnect')], default='score_limit', max_length=30),
        ),
        migrations.AddField(
            model_name='matchrecord',
            name='score_blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchrecord',
            name='score_red',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchrecord',
            name='winner_team',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='auth_app.matchrecord'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='matchplayer',
            unique_together={('match', 'user')},
        ),
    ]
